import { Router } from "express";
import { z } from "zod";
import { requireUser } from "./middleware.js";
import { authSchema, completionSchema, goalSchema, preferencesSchema, profileSchema, refreshSessionSchema, registerSchema, updateGoalSchema } from "./schemas.js";
import { AuthService, CoachService, DashboardService, GoalService, UserService } from "./services.js";
export const apiRouter=Router(); const auth=new AuthService(),goals=new GoalService(),users=new UserService(),dashboard=new DashboardService(),coach=new CoachService(); const id=z.string().uuid();
apiRouter.get("/health",(_q,r)=>r.json({data:{status:"ok",service:"goalpath-api"}}));
apiRouter.post("/auth/register",async(q,r)=>r.status(201).json({data:await auth.register(registerSchema.parse(q.body))}));
apiRouter.post("/auth/login",async(q,r)=>r.json({data:await auth.login(authSchema.parse(q.body))}));
apiRouter.post("/auth/refresh",async(q,r)=>r.json({data:await auth.refresh(refreshSessionSchema.parse(q.body).refreshToken)}));
apiRouter.get("/goals",requireUser,async(q,r)=>r.json({data:await goals.list(q.userId!)}));
apiRouter.get("/goals/:id",requireUser,async(q,r)=>r.json({data:await goals.get(q.userId!,id.parse(q.params.id))}));
apiRouter.post("/goals",requireUser,async(q,r)=>r.status(201).json({data:await goals.create(q.userId!,goalSchema.parse(q.body))}));
apiRouter.patch("/goals/:id",requireUser,async(q,r)=>r.json({data:await goals.update(q.userId!,id.parse(q.params.id),updateGoalSchema.parse(q.body))}));
apiRouter.delete("/goals/:id",requireUser,async(q,r)=>{await goals.remove(q.userId!,id.parse(q.params.id));r.status(204).send()});
apiRouter.get("/me",requireUser,async(q,r)=>r.json({data:await users.profile(q.userId!)}));
apiRouter.patch("/me",requireUser,async(q,r)=>r.json({data:await users.updateProfile(q.userId!,profileSchema.parse(q.body))}));
apiRouter.get("/me/preferences",requireUser,async(q,r)=>r.json({data:await users.preferences(q.userId!)}));
apiRouter.patch("/me/preferences",requireUser,async(q,r)=>r.json({data:await users.updatePreferences(q.userId!,preferencesSchema.parse(q.body))}));
apiRouter.get("/today",requireUser,async(q,r)=>r.json({data:await dashboard.today(q.userId!)}));
apiRouter.put("/habits/:id/completion",requireUser,async(q,r)=>{const input=completionSchema.parse(q.body);r.json({data:await dashboard.setCompletion(q.userId!,id.parse(q.params.id),input.completed,input.completionDate)})});
apiRouter.get("/progress",requireUser,async(q,r)=>r.json({data:await dashboard.progress(q.userId!)}));
apiRouter.get("/coach/sessions",requireUser,async(q,r)=>r.json({data:await coach.sessions(q.userId!)}));
apiRouter.post("/coach/sessions",requireUser,async(q,r)=>r.status(201).json({data:await coach.createSession(q.userId!,z.object({title:z.string().min(1).max(120).optional()}).parse(q.body).title)}));
apiRouter.get("/coach/sessions/:id/messages",requireUser,async(q,r)=>r.json({data:await coach.messages(q.userId!,id.parse(q.params.id))}));
apiRouter.post("/coach/sessions/:id/messages",requireUser,async(q,r)=>{const input=z.object({role:z.enum(["user","assistant"]).default("user"),content:z.string().min(1).max(5000)}).parse(q.body);r.status(201).json({data:await coach.addMessage(q.userId!,id.parse(q.params.id),input.role,input.content)})});
