create extension if not exists "pgcrypto";
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade,name text not null default 'GoalPath User',username text not null default '@goalpath',avatar_url text not null default '',level integer not null default 1 check(level>=1),xp integer not null default 0 check(xp>=0),streak_days integer not null default 0 check(streak_days>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.user_preferences (user_id uuid primary key references auth.users(id) on delete cascade,appearance text not null default 'system' check(appearance in('light','dark','system')),notifications jsonb not null default '[]'::jsonb,updated_at timestamptz not null default now());
create table if not exists public.goals (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,title text not null,category text not null default 'other' check(category in('language','fitness','skills','creativity','learning','other')),period text not null check(period in('1month','3months','6months','1year')),progress numeric(5,2) not null default 0 check(progress between 0 and 100),start_date timestamptz not null,target_date timestamptz not null,reminder_enabled boolean not null default true,notification_preference text not null default 'all' check(notification_preference in('all','important','none')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.habits (id uuid primary key default gen_random_uuid(),goal_id uuid not null references public.goals(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,title text not null,duration integer not null check(duration>0),difficulty text not null check(difficulty in('easy','medium','hard')),time_range text not null default 'anytime' check(time_range in('anytime','morning','afternoon','evening')),reminder_time time,active_days text[] not null default '{}',priority text not null default 'medium' check(priority in('low','medium','high')),created_at timestamptz not null default now());
create table if not exists public.habit_completions (id uuid primary key default gen_random_uuid(),habit_id uuid not null references public.habits(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,completion_date date not null default current_date,completed boolean not null default true,completed_at timestamptz not null default now(),unique(habit_id,completion_date));
create table if not exists public.coach_sessions (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,title text not null default 'New Session',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.coach_messages (id uuid primary key default gen_random_uuid(),session_id uuid not null references public.coach_sessions(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role text not null check(role in('user','assistant')),content text not null,created_at timestamptz not null default now());
create index if not exists goals_user_created_idx on public.goals(user_id,created_at desc);
create index if not exists habits_goal_idx on public.habits(goal_id);
create index if not exists completions_user_date_idx on public.habit_completions(user_id,completion_date desc);
create index if not exists coach_sessions_user_updated_idx on public.coach_sessions(user_id,updated_at desc);
alter table public.profiles enable row level security;
alter table public.user_preferences enable row level security;
alter table public.goals enable row level security;
alter table public.habits enable row level security;
alter table public.habit_completions enable row level security;
alter table public.coach_sessions enable row level security;
alter table public.coach_messages enable row level security;
drop policy if exists "profiles_owner" on public.profiles;
drop policy if exists "preferences_owner" on public.user_preferences;
drop policy if exists "goals_owner" on public.goals;
drop policy if exists "habits_owner" on public.habits;
drop policy if exists "completions_owner" on public.habit_completions;
drop policy if exists "coach_sessions_owner" on public.coach_sessions;
drop policy if exists "coach_messages_owner" on public.coach_messages;
create policy "profiles_owner" on public.profiles for all using (auth.uid()=id) with check (auth.uid()=id);
create policy "preferences_owner" on public.user_preferences for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "goals_owner" on public.goals for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "habits_owner" on public.habits for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "completions_owner" on public.habit_completions for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "coach_sessions_owner" on public.coach_sessions for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "coach_messages_owner" on public.coach_messages for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,name,username) values(new.id,coalesce(new.raw_user_meta_data->>'name','GoalPath User'),'@'||split_part(new.email,'@',1)); insert into public.user_preferences(user_id) values(new.id); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
